// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proxy/mieru/config.proto

package mieru

import (
	protocol "github.com/xtls/xray-core/common/protocol"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Account contains the credentials mieru authenticates with. Unlike most
// protocols here mieru keys on a user name as well as a password.
type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proxy_mieru_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_mieru_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proxy_mieru_config_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Account) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type ClientConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A single server endpoint. mieru's own client config takes a list, but a
	// node in this app is always one server, and the node list is what gives the
	// user a choice between them.
	Server *protocol.ServerEndpoint `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	// "TCP" or "UDP" — the transport mieru uses to reach the server, not the
	// network of the proxied traffic. Defaults to TCP when empty.
	Transport string `protobuf:"bytes,2,opt,name=transport,proto3" json:"transport,omitempty"`
	// Inclusive port range, for servers that listen on many ports so a single
	// blocked port does not take the node down. Mutually exclusive with
	// server.port; exactly one of the two must be set.
	PortRangeStart uint32 `protobuf:"varint,3,opt,name=port_range_start,json=portRangeStart,proto3" json:"port_range_start,omitempty"`
	PortRangeEnd   uint32 `protobuf:"varint,4,opt,name=port_range_end,json=portRangeEnd,proto3" json:"port_range_end,omitempty"`
	// Connection multiplexing level: "MULTIPLEXING_OFF", "MULTIPLEXING_LOW",
	// "MULTIPLEXING_MIDDLE" or "MULTIPLEXING_HIGH". Empty means mieru's default.
	Multiplexing string `protobuf:"bytes,5,opt,name=multiplexing,proto3" json:"multiplexing,omitempty"`
	// Maximum transmission unit for the UDP transport. Empty means mieru's
	// default. Has no effect on the TCP transport.
	Mtu int32 `protobuf:"varint,6,opt,name=mtu,proto3" json:"mtu,omitempty"`
	// "HANDSHAKE_STANDARD" waits for the server to reach the destination before
	// sending payload (1-RTT); "HANDSHAKE_NO_WAIT" sends both at once (0-RTT).
	// Empty means mieru's default, which behaves as HANDSHAKE_STANDARD.
	HandshakeMode string `protobuf:"bytes,7,opt,name=handshake_mode,json=handshakeMode,proto3" json:"handshake_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientConfig) Reset() {
	*x = ClientConfig{}
	mi := &file_proxy_mieru_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientConfig) ProtoMessage() {}

func (x *ClientConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_mieru_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientConfig.ProtoReflect.Descriptor instead.
func (*ClientConfig) Descriptor() ([]byte, []int) {
	return file_proxy_mieru_config_proto_rawDescGZIP(), []int{1}
}

func (x *ClientConfig) GetServer() *protocol.ServerEndpoint {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *ClientConfig) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *ClientConfig) GetPortRangeStart() uint32 {
	if x != nil {
		return x.PortRangeStart
	}
	return 0
}

func (x *ClientConfig) GetPortRangeEnd() uint32 {
	if x != nil {
		return x.PortRangeEnd
	}
	return 0
}

func (x *ClientConfig) GetMultiplexing() string {
	if x != nil {
		return x.Multiplexing
	}
	return ""
}

func (x *ClientConfig) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *ClientConfig) GetHandshakeMode() string {
	if x != nil {
		return x.HandshakeMode
	}
	return ""
}

type ServerConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Users allowed to connect. mieru derives each session key from the user name
	// and password together, so both halves of the account matter. The list can be
	// changed at runtime through the handler service without dropping the
	// listener; see proxy/mieru/inbound.go.
	Users []*protocol.User `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	// "TCP" or "UDP" — the underlay mieru accepts connections on, not the network
	// of the proxied traffic. Defaults to TCP when empty.
	Transport string `protobuf:"bytes,2,opt,name=transport,proto3" json:"transport,omitempty"`
	// Maximum transmission unit for the UDP underlay. Empty means mieru's
	// default. Has no effect on the TCP underlay.
	Mtu int32 `protobuf:"varint,3,opt,name=mtu,proto3" json:"mtu,omitempty"`
	// Accepted for symmetry with ClientConfig. Multiplexing is chosen by the
	// client and negotiated in-band — mieru's own server config has no such field
	// — so this is validated and otherwise unused.
	Multiplexing  string `protobuf:"bytes,4,opt,name=multiplexing,proto3" json:"multiplexing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_proxy_mieru_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_mieru_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_proxy_mieru_config_proto_rawDescGZIP(), []int{2}
}

func (x *ServerConfig) GetUsers() []*protocol.User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ServerConfig) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *ServerConfig) GetMtu() int32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *ServerConfig) GetMultiplexing() string {
	if x != nil {
		return x.Multiplexing
	}
	return ""
}

var File_proxy_mieru_config_proto protoreflect.FileDescriptor

const file_proxy_mieru_config_proto_rawDesc = "" +
	"\n" +
	"\x18proxy/mieru/config.proto\x12\x10xray.proxy.mieru\x1a\x1acommon/protocol/user.proto\x1a!common/protocol/server_spec.proto\"A\n" +
	"\aAccount\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"\x97\x02\n" +
	"\fClientConfig\x12<\n" +
	"\x06server\x18\x01 \x01(\v2$.xray.common.protocol.ServerEndpointR\x06server\x12\x1c\n" +
	"\ttransport\x18\x02 \x01(\tR\ttransport\x12(\n" +
	"\x10port_range_start\x18\x03 \x01(\rR\x0eportRangeStart\x12$\n" +
	"\x0eport_range_end\x18\x04 \x01(\rR\fportRangeEnd\x12\"\n" +
	"\fmultiplexing\x18\x05 \x01(\tR\fmultiplexing\x12\x10\n" +
	"\x03mtu\x18\x06 \x01(\x05R\x03mtu\x12%\n" +
	"\x0ehandshake_mode\x18\a \x01(\tR\rhandshakeMode\"\x94\x01\n" +
	"\fServerConfig\x120\n" +
	"\x05users\x18\x01 \x03(\v2\x1a.xray.common.protocol.UserR\x05users\x12\x1c\n" +
	"\ttransport\x18\x02 \x01(\tR\ttransport\x12\x10\n" +
	"\x03mtu\x18\x03 \x01(\x05R\x03mtu\x12\"\n" +
	"\fmultiplexing\x18\x04 \x01(\tR\fmultiplexingBR\n" +
	"\x14com.xray.proxy.mieruP\x01Z%github.com/xtls/xray-core/proxy/mieru\xaa\x02\x10Xray.Proxy.Mierub\x06proto3"

var (
	file_proxy_mieru_config_proto_rawDescOnce sync.Once
	file_proxy_mieru_config_proto_rawDescData []byte
)

func file_proxy_mieru_config_proto_rawDescGZIP() []byte {
	file_proxy_mieru_config_proto_rawDescOnce.Do(func() {
		file_proxy_mieru_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_mieru_config_proto_rawDesc), len(file_proxy_mieru_config_proto_rawDesc)))
	})
	return file_proxy_mieru_config_proto_rawDescData
}

var file_proxy_mieru_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proxy_mieru_config_proto_goTypes = []any{
	(*Account)(nil),                 // 0: xray.proxy.mieru.Account
	(*ClientConfig)(nil),            // 1: xray.proxy.mieru.ClientConfig
	(*ServerConfig)(nil),            // 2: xray.proxy.mieru.ServerConfig
	(*protocol.ServerEndpoint)(nil), // 3: xray.common.protocol.ServerEndpoint
	(*protocol.User)(nil),           // 4: xray.common.protocol.User
}
var file_proxy_mieru_config_proto_depIdxs = []int32{
	3, // 0: xray.proxy.mieru.ClientConfig.server:type_name -> xray.common.protocol.ServerEndpoint
	4, // 1: xray.proxy.mieru.ServerConfig.users:type_name -> xray.common.protocol.User
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proxy_mieru_config_proto_init() }
func file_proxy_mieru_config_proto_init() {
	if File_proxy_mieru_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_mieru_config_proto_rawDesc), len(file_proxy_mieru_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_mieru_config_proto_goTypes,
		DependencyIndexes: file_proxy_mieru_config_proto_depIdxs,
		MessageInfos:      file_proxy_mieru_config_proto_msgTypes,
	}.Build()
	File_proxy_mieru_config_proto = out.File
	file_proxy_mieru_config_proto_goTypes = nil
	file_proxy_mieru_config_proto_depIdxs = nil
}
